version: '3.1'

services:
  batch_db:
    container_name: job_repository
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: job_repository
      TZ: "UTC"
  redis:
    container_name: redis_cache
    image: redis/redis-stack:7.2.0-v9
    ports:
      - "6379:6379"
      - "8001:8001"
  mongo_db:
    container_name: aggregated_logs_db
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: aggregated_logs


