spring:
  application:
    name: Search Autocomplete System
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
mongodb:
  querydb:
    port: 27017
    username: user
    password: password
    database: aggregated_query_logs
    host: localhost
    authentication-database: admin
    auto-index-creation: true
  triedb:
    port: 27017
    username: user
    password: password
    database: trie_db
    host: localhost
    authentication-database: admin
    auto-index-creation: true
