spring:
  application:
    name: Search Autocomplete System
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  web:
    resources:
      add-mappings: false
server:
  trace:
    true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
mongodb:
  querydb:
    port: 27017
    username: user
    password: password
    database: aggregated_query_logs
    host: localhost
    authentication-database: admin
    auto-index-creation: true
  triedb:
    port: 27017
    username: user
    password: password
    database: trie_db
    host: localhost
    authentication-database: admin
    auto-index-creation: true
