spring:
  profiles:
    active: dev
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  web:
    resources:
      add-mappings: false
  cache:
    type: redis
server:
  trace:
    true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

